### PR TITLE
chore: migrate to dart sass

### LINKED ISSUE #325: Site is no longer updating
## Description of the issue

The dev branch is not loading automatically into main, so site is not being updated.

### Steps to reproduce

The CI appears to be blocked by a network problem, as seen here https://github.com/RedHatOfficial/RedHatOfficial.github.io/runs/7658463790

One of my teammates looked into it, and believes the root cause is from this commit:

https://github.com/RedHatOfficial/RedHatOfficial.github.io/commit/e3df18983153b18c5d12c7ac539706fa6f58aabb

Which somehow has embedded a internal RH URL.

He does not know npm, and maybe that's a false lead, but he thinks it tries to download some deps, and can't get it from the nexus installation and fails.

But maybe it is broken before and the nexus DNS error is just a symptom and not the root cause.

More information, from him, when he tried to build it locally:

"The problem is that almost all dependencies are out of date, more or
less. So I relaxed the version number in package.json, remove the lock
file and hoped for the best.

"This showed that for some reason, we need the version 5.x of webpack.
Less than this, it conflits with a specific deps, more it conflict
with another dependency.

"Once I got that fixed, a issue with uglifyjs-webpack-plugin appeared.
So I removed it, and fixed the webpack buildconfig.

"The the syntax of one or two plugins changed, that I fixed as well.

"Now, it build, but the angular application do not work and show no
error anywhere. The bundle.js is loaded, etc. It just show nothing
anywhere.

"So if a webdev can take a look, that would help, because I am at the
limit of what I can do without involving a miracle :)"

### Expected behavior

The site should update, and it's not.

### PR DESCRIPTION
**Pull request by bennypowers**
fixes #325 by updating sass dependencies

### Testing instructions

1. `npm start`
2. `npm build`

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

## Further enhancement
I'm interested in writing a migration from angular to [lit](https://lit.dev)+[red-hat-design-system](https://ux.redhat.com)? This would drastically reduce both the amount of code in this repo as well as the code over-the-wire to end user (thus improving loading performance), while updating the tech stack.

### CODE REVIEW

**Comment by bennypowers** [comment]
There was an unrelated build failure which i fixed in [093327b](https://github.com/RedHatOfficial/RedHatOfficial.github.io/pull/333/commits/093327ba7c9904398ba94f598fe5b92c11aa9a45). PTAL @bproffitt

**Review by bproffitt — APPROVED** [review]

**Comment by bennypowers** [comment]
https://github.com/RedHatOfficial/RedHatOfficial.github.io/actions/runs/3316451348/jobs/5488211102

> Error: Dependencies lock file is not found in /home/runner/work/RedHatOfficial.github.io/RedHatOfficial.github.io. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock

🤔

**Comment by bproffitt** [comment]
Solution? I just see a lot of new PRs to bump tools up, but unclear if
that's related or coincedence.

BKP

**Comment by bennypowers** [comment]
not clear to me atm. i thought it could be that this action is running on the branch which contains the build gh-pages site, which wouldn't have the package-lock. does that seem likely to you?

**Pull request merged**
