### PR TITLE
Automate update web

### PR DESCRIPTION
**Pull request by aljesusg**
Issue #106 

With this your site is uploaded each time a PR is merged in dev.

You need to set in travis a environment called: GH_PAGES_TOKEN with a token with access and push to master.

### CODE REVIEW

**Comment by bproffitt** [comment]
@greg-hellings Is this something you can help with? (Personal token requirement mentioned by @aljesusg ?) Or is it something we need to do?

**Comment by greg-hellings** [comment]
@bproffitt Anyone who is a GitHub user can create a token, but my token would not be useful here. Someone with administrative rights on the repository needs to create a token. Once you have the token by following the directions that @aljesusg mentions above, you can add it to your Travis job.

1. Log into Travis and select the job for this repo
2. At the top right click the "More Options" menu and select "Settings"
3. Part way down the page, in the section titled "Environment Variables" create a new variable with the name GH_PAGES_TOKEN and add the token value you got above.

Note that if your token includes any special characters (like $, ", ', {, (, }, ), a space or similar) you might have to "escape" those. But hopefully GitHub is smart enough to not generate tokens like that. Usually a token is nothing but letters and numbers.

**Comment by bproffitt** [comment]
@aljesusg I made a token with full repo access and added it per the instructions @greg-hellings outlined above.Anything else I need to do?

**Comment by aljesusg** [comment]
No, it should be update the website of GitHub pages Everytime you merge in Dev

**Comment by bproffitt** [comment]
@castastrophe @ReeseSThomp I would love to have this featured added, but you guys know the app better than me. Can you please approve?

**Comment by aljesusg** [comment]
Thanks @bproffitt and congrats !!! It's running ^^
screenshot_20180330-020149__01

**Comment by bproffitt** [comment]
Thank _you_ @aljesusg ! Really appreciate it!

**Pull request merged**
