### PR TITLE
Add Drupal project

### PR DESCRIPTION
**Pull request by ElijahLynn**

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Oh, I think this project isn't applicable since it isn't hosted on Github. Feel free to close this.

**Comment by castastrophe** [comment]
@bproffitt I think we need to back this change out.  It's not a Red Hat project and it's not hosted on GitHub; it's an open source CMS that we utilize and contribute to. Am I correct in that @ElijahLynn?

**Comment by bproffitt** [comment]
Right, and on further review, @ElijahLynn , Drupal hosts it code on git.drupal.org, not GitHub. Removing.

**Comment by ElijahLynn** [comment]
Thanks

**Pull request merged**
